/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IClawPactEscrow {
  export type EscrowRecordStruct = {
    requester: AddressLike;
    provider: AddressLike;
    rewardAmount: BigNumberish;
    requesterDeposit: BigNumberish;
    depositConsumed: BigNumberish;
    token: AddressLike;
    state: BigNumberish;
    taskHash: BytesLike;
    latestDeliveryHash: BytesLike;
    latestCriteriaHash: BytesLike;
    deliveryDurationSeconds: BigNumberish;
    deliveryDeadline: BigNumberish;
    acceptanceDeadline: BigNumberish;
    confirmationDeadline: BigNumberish;
    maxRevisions: BigNumberish;
    currentRevision: BigNumberish;
    criteriaCount: BigNumberish;
    declineCount: BigNumberish;
    acceptanceWindowHours: BigNumberish;
  };

  export type EscrowRecordStructOutput = [
    requester: string,
    provider: string,
    rewardAmount: bigint,
    requesterDeposit: bigint,
    depositConsumed: bigint,
    token: string,
    state: bigint,
    taskHash: string,
    latestDeliveryHash: string,
    latestCriteriaHash: string,
    deliveryDurationSeconds: bigint,
    deliveryDeadline: bigint,
    acceptanceDeadline: bigint,
    confirmationDeadline: bigint,
    maxRevisions: bigint,
    currentRevision: bigint,
    criteriaCount: bigint,
    declineCount: bigint,
    acceptanceWindowHours: bigint
  ] & {
    requester: string;
    provider: string;
    rewardAmount: bigint;
    requesterDeposit: bigint;
    depositConsumed: bigint;
    token: string;
    state: bigint;
    taskHash: string;
    latestDeliveryHash: string;
    latestCriteriaHash: string;
    deliveryDurationSeconds: bigint;
    deliveryDeadline: bigint;
    acceptanceDeadline: bigint;
    confirmationDeadline: bigint;
    maxRevisions: bigint;
    currentRevision: bigint;
    criteriaCount: bigint;
    declineCount: bigint;
    acceptanceWindowHours: bigint;
  };
}

export interface ClawPactEscrowV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "ASSIGNMENT_TYPEHASH"
      | "CONFIRMATION_WINDOW"
      | "MAX_DECLINE_COUNT"
      | "MIN_PASS_RATE"
      | "PLATFORM_FEE_BPS"
      | "UPGRADE_INTERFACE_VERSION"
      | "abandonTask"
      | "acceptDelivery"
      | "allowedTokens"
      | "assignmentNonces"
      | "cancelTask"
      | "claimAcceptanceTimeout"
      | "claimConfirmationTimeout"
      | "claimDeliveryTimeout"
      | "claimTask"
      | "confirmTask"
      | "createEscrow"
      | "declineTask"
      | "eip712Domain"
      | "escrowFundWeights"
      | "escrows"
      | "getDomainSeparator"
      | "getEscrow"
      | "getFundWeight"
      | "getFundWeights"
      | "initialize"
      | "nextEscrowId"
      | "owner"
      | "platformFund"
      | "platformSigner"
      | "proxiableUUID"
      | "renounceOwnership"
      | "requestRevision"
      | "setAllowedToken"
      | "setPlatformFund"
      | "setPlatformSigner"
      | "submitDelivery"
      | "transferOwnership"
      | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DeliveryAccepted"
      | "DeliverySubmitted"
      | "EIP712DomainChanged"
      | "EscrowCreated"
      | "Initialized"
      | "OwnershipTransferred"
      | "RevisionRequested"
      | "TaskAbandoned"
      | "TaskAutoSettled"
      | "TaskCancelled"
      | "TaskClaimed"
      | "TaskConfirmed"
      | "TaskDeclined"
      | "TaskSuspendedAfterDeclines"
      | "TimeoutClaimed"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ASSIGNMENT_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CONFIRMATION_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_DECLINE_COUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_PASS_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "abandonTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "acceptDelivery",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allowedTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "assignmentNonces",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimAcceptanceTimeout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimConfirmationTimeout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimDeliveryTimeout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTask",
    values: [BigNumberish, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createEscrow",
    values: [
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish[],
      AddressLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "declineTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "escrowFundWeights",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "escrows",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDomainSeparator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFundWeight",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFundWeights",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextEscrowId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFund",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformSigner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestRevision",
    values: [BigNumberish, BytesLike, boolean[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setAllowedToken",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFund",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitDelivery",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ASSIGNMENT_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CONFIRMATION_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_DECLINE_COUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_PASS_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "abandonTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptDelivery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assignmentNonces",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimAcceptanceTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimConfirmationTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimDeliveryTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confirmTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "declineTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escrowFundWeights",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrows", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDomainSeparator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEscrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFundWeight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFundWeights",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextEscrowId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRevision",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAllowedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitDelivery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace DeliveryAcceptedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    providerPayout: BigNumberish,
    platformFee: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    providerPayout: bigint,
    platformFee: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    providerPayout: bigint;
    platformFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeliverySubmittedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    deliveryHash: BytesLike,
    revision: BigNumberish,
    acceptanceDeadline: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    deliveryHash: string,
    revision: bigint,
    acceptanceDeadline: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    deliveryHash: string;
    revision: bigint;
    acceptanceDeadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowCreatedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    requester: AddressLike,
    taskHash: BytesLike,
    rewardAmount: BigNumberish,
    requesterDeposit: BigNumberish,
    token: AddressLike,
    deliveryDurationSeconds: BigNumberish,
    maxRevisions: BigNumberish,
    acceptanceWindowHours: BigNumberish,
    criteriaCount: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    requester: string,
    taskHash: string,
    rewardAmount: bigint,
    requesterDeposit: bigint,
    token: string,
    deliveryDurationSeconds: bigint,
    maxRevisions: bigint,
    acceptanceWindowHours: bigint,
    criteriaCount: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    requester: string;
    taskHash: string;
    rewardAmount: bigint;
    requesterDeposit: bigint;
    token: string;
    deliveryDurationSeconds: bigint;
    maxRevisions: bigint;
    acceptanceWindowHours: bigint;
    criteriaCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevisionRequestedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    reasonHash: BytesLike,
    criteriaResultsHash: BytesLike,
    currentRevision: BigNumberish,
    depositPenalty: BigNumberish,
    passRate: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    reasonHash: string,
    criteriaResultsHash: string,
    currentRevision: bigint,
    depositPenalty: bigint,
    passRate: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    reasonHash: string;
    criteriaResultsHash: string;
    currentRevision: bigint;
    depositPenalty: bigint;
    passRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskAbandonedEvent {
  export type InputTuple = [escrowId: BigNumberish, provider: AddressLike];
  export type OutputTuple = [escrowId: bigint, provider: string];
  export interface OutputObject {
    escrowId: bigint;
    provider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskAutoSettledEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    passRate: BigNumberish,
    providerShare: BigNumberish,
    requesterRefund: BigNumberish,
    platformFee: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    passRate: bigint,
    providerShare: bigint,
    requesterRefund: bigint,
    platformFee: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    passRate: bigint;
    providerShare: bigint;
    requesterRefund: bigint;
    platformFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCancelledEvent {
  export type InputTuple = [escrowId: BigNumberish, compensation: BigNumberish];
  export type OutputTuple = [escrowId: bigint, compensation: bigint];
  export interface OutputObject {
    escrowId: bigint;
    compensation: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskClaimedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    provider: AddressLike,
    confirmationDeadline: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    provider: string,
    confirmationDeadline: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    provider: string;
    confirmationDeadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskConfirmedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    provider: AddressLike,
    deliveryDeadline: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    provider: string,
    deliveryDeadline: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    provider: string;
    deliveryDeadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskDeclinedEvent {
  export type InputTuple = [escrowId: BigNumberish, provider: AddressLike];
  export type OutputTuple = [escrowId: bigint, provider: string];
  export interface OutputObject {
    escrowId: bigint;
    provider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskSuspendedAfterDeclinesEvent {
  export type InputTuple = [escrowId: BigNumberish, declineCount: BigNumberish];
  export type OutputTuple = [escrowId: bigint, declineCount: bigint];
  export interface OutputObject {
    escrowId: bigint;
    declineCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimeoutClaimedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    previousState: BigNumberish,
    claimedBy: AddressLike
  ];
  export type OutputTuple = [
    escrowId: bigint,
    previousState: bigint,
    claimedBy: string
  ];
  export interface OutputObject {
    escrowId: bigint;
    previousState: bigint;
    claimedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ClawPactEscrowV2 extends BaseContract {
  connect(runner?: ContractRunner | null): ClawPactEscrowV2;
  waitForDeployment(): Promise<this>;

  interface: ClawPactEscrowV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ASSIGNMENT_TYPEHASH: TypedContractMethod<[], [string], "view">;

  CONFIRMATION_WINDOW: TypedContractMethod<[], [bigint], "view">;

  MAX_DECLINE_COUNT: TypedContractMethod<[], [bigint], "view">;

  MIN_PASS_RATE: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  abandonTask: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  acceptDelivery: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  allowedTokens: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  assignmentNonces: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  cancelTask: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimAcceptanceTimeout: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimConfirmationTimeout: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimDeliveryTimeout: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimTask: TypedContractMethod<
    [
      escrowId: BigNumberish,
      nonce: BigNumberish,
      expiredAt: BigNumberish,
      platformSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  confirmTask: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createEscrow: TypedContractMethod<
    [
      taskHash: BytesLike,
      deliveryDurationSeconds: BigNumberish,
      maxRevisions: BigNumberish,
      acceptanceWindowHours: BigNumberish,
      criteriaCount: BigNumberish,
      fundWeights: BigNumberish[],
      token: AddressLike,
      totalAmount: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  declineTask: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  escrowFundWeights: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  escrows: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        requester: string;
        provider: string;
        rewardAmount: bigint;
        requesterDeposit: bigint;
        depositConsumed: bigint;
        token: string;
        state: bigint;
        taskHash: string;
        latestDeliveryHash: string;
        latestCriteriaHash: string;
        deliveryDurationSeconds: bigint;
        deliveryDeadline: bigint;
        acceptanceDeadline: bigint;
        confirmationDeadline: bigint;
        maxRevisions: bigint;
        currentRevision: bigint;
        criteriaCount: bigint;
        declineCount: bigint;
        acceptanceWindowHours: bigint;
      }
    ],
    "view"
  >;

  getDomainSeparator: TypedContractMethod<[], [string], "view">;

  getEscrow: TypedContractMethod<
    [escrowId: BigNumberish],
    [IClawPactEscrow.EscrowRecordStructOutput],
    "view"
  >;

  getFundWeight: TypedContractMethod<
    [escrowId: BigNumberish, criteriaIndex: BigNumberish],
    [bigint],
    "view"
  >;

  getFundWeights: TypedContractMethod<
    [escrowId: BigNumberish],
    [bigint[]],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      _platformSigner: AddressLike,
      _platformFund: AddressLike,
      _owner: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  nextEscrowId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  platformFund: TypedContractMethod<[], [string], "view">;

  platformSigner: TypedContractMethod<[], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestRevision: TypedContractMethod<
    [escrowId: BigNumberish, reasonHash: BytesLike, criteriaResults: boolean[]],
    [void],
    "nonpayable"
  >;

  setAllowedToken: TypedContractMethod<
    [token: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  setPlatformFund: TypedContractMethod<
    [newFund: AddressLike],
    [void],
    "nonpayable"
  >;

  setPlatformSigner: TypedContractMethod<
    [newSigner: AddressLike],
    [void],
    "nonpayable"
  >;

  submitDelivery: TypedContractMethod<
    [escrowId: BigNumberish, deliveryHash: BytesLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ASSIGNMENT_TYPEHASH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CONFIRMATION_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_DECLINE_COUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_PASS_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "abandonTask"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "acceptDelivery"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allowedTokens"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "assignmentNonces"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelTask"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimAcceptanceTimeout"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimConfirmationTimeout"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimDeliveryTimeout"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimTask"
  ): TypedContractMethod<
    [
      escrowId: BigNumberish,
      nonce: BigNumberish,
      expiredAt: BigNumberish,
      platformSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confirmTask"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createEscrow"
  ): TypedContractMethod<
    [
      taskHash: BytesLike,
      deliveryDurationSeconds: BigNumberish,
      maxRevisions: BigNumberish,
      acceptanceWindowHours: BigNumberish,
      criteriaCount: BigNumberish,
      fundWeights: BigNumberish[],
      token: AddressLike,
      totalAmount: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "declineTask"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "escrowFundWeights"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "escrows"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        requester: string;
        provider: string;
        rewardAmount: bigint;
        requesterDeposit: bigint;
        depositConsumed: bigint;
        token: string;
        state: bigint;
        taskHash: string;
        latestDeliveryHash: string;
        latestCriteriaHash: string;
        deliveryDurationSeconds: bigint;
        deliveryDeadline: bigint;
        acceptanceDeadline: bigint;
        confirmationDeadline: bigint;
        maxRevisions: bigint;
        currentRevision: bigint;
        criteriaCount: bigint;
        declineCount: bigint;
        acceptanceWindowHours: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDomainSeparator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEscrow"
  ): TypedContractMethod<
    [escrowId: BigNumberish],
    [IClawPactEscrow.EscrowRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFundWeight"
  ): TypedContractMethod<
    [escrowId: BigNumberish, criteriaIndex: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFundWeights"
  ): TypedContractMethod<[escrowId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _platformSigner: AddressLike,
      _platformFund: AddressLike,
      _owner: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextEscrowId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFund"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformSigner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestRevision"
  ): TypedContractMethod<
    [escrowId: BigNumberish, reasonHash: BytesLike, criteriaResults: boolean[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAllowedToken"
  ): TypedContractMethod<
    [token: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPlatformFund"
  ): TypedContractMethod<[newFund: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformSigner"
  ): TypedContractMethod<[newSigner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitDelivery"
  ): TypedContractMethod<
    [escrowId: BigNumberish, deliveryHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "DeliveryAccepted"
  ): TypedContractEvent<
    DeliveryAcceptedEvent.InputTuple,
    DeliveryAcceptedEvent.OutputTuple,
    DeliveryAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "DeliverySubmitted"
  ): TypedContractEvent<
    DeliverySubmittedEvent.InputTuple,
    DeliverySubmittedEvent.OutputTuple,
    DeliverySubmittedEvent.OutputObject
  >;
  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowCreated"
  ): TypedContractEvent<
    EscrowCreatedEvent.InputTuple,
    EscrowCreatedEvent.OutputTuple,
    EscrowCreatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RevisionRequested"
  ): TypedContractEvent<
    RevisionRequestedEvent.InputTuple,
    RevisionRequestedEvent.OutputTuple,
    RevisionRequestedEvent.OutputObject
  >;
  getEvent(
    key: "TaskAbandoned"
  ): TypedContractEvent<
    TaskAbandonedEvent.InputTuple,
    TaskAbandonedEvent.OutputTuple,
    TaskAbandonedEvent.OutputObject
  >;
  getEvent(
    key: "TaskAutoSettled"
  ): TypedContractEvent<
    TaskAutoSettledEvent.InputTuple,
    TaskAutoSettledEvent.OutputTuple,
    TaskAutoSettledEvent.OutputObject
  >;
  getEvent(
    key: "TaskCancelled"
  ): TypedContractEvent<
    TaskCancelledEvent.InputTuple,
    TaskCancelledEvent.OutputTuple,
    TaskCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TaskClaimed"
  ): TypedContractEvent<
    TaskClaimedEvent.InputTuple,
    TaskClaimedEvent.OutputTuple,
    TaskClaimedEvent.OutputObject
  >;
  getEvent(
    key: "TaskConfirmed"
  ): TypedContractEvent<
    TaskConfirmedEvent.InputTuple,
    TaskConfirmedEvent.OutputTuple,
    TaskConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "TaskDeclined"
  ): TypedContractEvent<
    TaskDeclinedEvent.InputTuple,
    TaskDeclinedEvent.OutputTuple,
    TaskDeclinedEvent.OutputObject
  >;
  getEvent(
    key: "TaskSuspendedAfterDeclines"
  ): TypedContractEvent<
    TaskSuspendedAfterDeclinesEvent.InputTuple,
    TaskSuspendedAfterDeclinesEvent.OutputTuple,
    TaskSuspendedAfterDeclinesEvent.OutputObject
  >;
  getEvent(
    key: "TimeoutClaimed"
  ): TypedContractEvent<
    TimeoutClaimedEvent.InputTuple,
    TimeoutClaimedEvent.OutputTuple,
    TimeoutClaimedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "DeliveryAccepted(uint256,uint256,uint256)": TypedContractEvent<
      DeliveryAcceptedEvent.InputTuple,
      DeliveryAcceptedEvent.OutputTuple,
      DeliveryAcceptedEvent.OutputObject
    >;
    DeliveryAccepted: TypedContractEvent<
      DeliveryAcceptedEvent.InputTuple,
      DeliveryAcceptedEvent.OutputTuple,
      DeliveryAcceptedEvent.OutputObject
    >;

    "DeliverySubmitted(uint256,bytes32,uint8,uint64)": TypedContractEvent<
      DeliverySubmittedEvent.InputTuple,
      DeliverySubmittedEvent.OutputTuple,
      DeliverySubmittedEvent.OutputObject
    >;
    DeliverySubmitted: TypedContractEvent<
      DeliverySubmittedEvent.InputTuple,
      DeliverySubmittedEvent.OutputTuple,
      DeliverySubmittedEvent.OutputObject
    >;

    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "EscrowCreated(uint256,address,bytes32,uint256,uint256,address,uint64,uint8,uint8,uint8)": TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;
    EscrowCreated: TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RevisionRequested(uint256,bytes32,bytes32,uint8,uint256,uint8)": TypedContractEvent<
      RevisionRequestedEvent.InputTuple,
      RevisionRequestedEvent.OutputTuple,
      RevisionRequestedEvent.OutputObject
    >;
    RevisionRequested: TypedContractEvent<
      RevisionRequestedEvent.InputTuple,
      RevisionRequestedEvent.OutputTuple,
      RevisionRequestedEvent.OutputObject
    >;

    "TaskAbandoned(uint256,address)": TypedContractEvent<
      TaskAbandonedEvent.InputTuple,
      TaskAbandonedEvent.OutputTuple,
      TaskAbandonedEvent.OutputObject
    >;
    TaskAbandoned: TypedContractEvent<
      TaskAbandonedEvent.InputTuple,
      TaskAbandonedEvent.OutputTuple,
      TaskAbandonedEvent.OutputObject
    >;

    "TaskAutoSettled(uint256,uint8,uint256,uint256,uint256)": TypedContractEvent<
      TaskAutoSettledEvent.InputTuple,
      TaskAutoSettledEvent.OutputTuple,
      TaskAutoSettledEvent.OutputObject
    >;
    TaskAutoSettled: TypedContractEvent<
      TaskAutoSettledEvent.InputTuple,
      TaskAutoSettledEvent.OutputTuple,
      TaskAutoSettledEvent.OutputObject
    >;

    "TaskCancelled(uint256,uint256)": TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;
    TaskCancelled: TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;

    "TaskClaimed(uint256,address,uint64)": TypedContractEvent<
      TaskClaimedEvent.InputTuple,
      TaskClaimedEvent.OutputTuple,
      TaskClaimedEvent.OutputObject
    >;
    TaskClaimed: TypedContractEvent<
      TaskClaimedEvent.InputTuple,
      TaskClaimedEvent.OutputTuple,
      TaskClaimedEvent.OutputObject
    >;

    "TaskConfirmed(uint256,address,uint64)": TypedContractEvent<
      TaskConfirmedEvent.InputTuple,
      TaskConfirmedEvent.OutputTuple,
      TaskConfirmedEvent.OutputObject
    >;
    TaskConfirmed: TypedContractEvent<
      TaskConfirmedEvent.InputTuple,
      TaskConfirmedEvent.OutputTuple,
      TaskConfirmedEvent.OutputObject
    >;

    "TaskDeclined(uint256,address)": TypedContractEvent<
      TaskDeclinedEvent.InputTuple,
      TaskDeclinedEvent.OutputTuple,
      TaskDeclinedEvent.OutputObject
    >;
    TaskDeclined: TypedContractEvent<
      TaskDeclinedEvent.InputTuple,
      TaskDeclinedEvent.OutputTuple,
      TaskDeclinedEvent.OutputObject
    >;

    "TaskSuspendedAfterDeclines(uint256,uint8)": TypedContractEvent<
      TaskSuspendedAfterDeclinesEvent.InputTuple,
      TaskSuspendedAfterDeclinesEvent.OutputTuple,
      TaskSuspendedAfterDeclinesEvent.OutputObject
    >;
    TaskSuspendedAfterDeclines: TypedContractEvent<
      TaskSuspendedAfterDeclinesEvent.InputTuple,
      TaskSuspendedAfterDeclinesEvent.OutputTuple,
      TaskSuspendedAfterDeclinesEvent.OutputObject
    >;

    "TimeoutClaimed(uint256,uint8,address)": TypedContractEvent<
      TimeoutClaimedEvent.InputTuple,
      TimeoutClaimedEvent.OutputTuple,
      TimeoutClaimedEvent.OutputObject
    >;
    TimeoutClaimed: TypedContractEvent<
      TimeoutClaimedEvent.InputTuple,
      TimeoutClaimedEvent.OutputTuple,
      TimeoutClaimedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
