/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IClawPactEscrow,
  IClawPactEscrowInterface,
} from "../../../src/interfaces/IClawPactEscrow";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "escrowId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "providerPayout",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "platformFee",
        type: "uint256",
      },
    ],
    name: "DeliveryAccepted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "escrowId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "deliveryHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "revision",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "acceptanceDeadline",
        type: "uint64",
      },
    ],
    name: "DeliverySubmitted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "escrowId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "requester",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "taskHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "rewardAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "requesterDeposit",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "deliveryDurationSeconds",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "maxRevisions",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "acceptanceWindowHours",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "criteriaCount",
        type: "uint8",
      },
    ],
    name: "EscrowCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "escrowId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "reasonHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "criteriaResultsHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "currentRevision",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "depositPenalty",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "passRate",
        type: "uint8",
      },
    ],
    name: "RevisionRequested",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "escrowId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "provider",
        type: "address",
      },
    ],
    name: "TaskAbandoned",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "escrowId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "passRate",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "providerShare",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "requesterRefund",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "platformFee",
        type: "uint256",
      },
    ],
    name: "TaskAutoSettled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "escrowId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "compensation",
        type: "uint256",
      },
    ],
    name: "TaskCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "escrowId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "provider",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "confirmationDeadline",
        type: "uint64",
      },
    ],
    name: "TaskClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "escrowId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "provider",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "deliveryDeadline",
        type: "uint64",
      },
    ],
    name: "TaskConfirmed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "escrowId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "provider",
        type: "address",
      },
    ],
    name: "TaskDeclined",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "escrowId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "declineCount",
        type: "uint8",
      },
    ],
    name: "TaskSuspendedAfterDeclines",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "escrowId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "enum IClawPactEscrow.TaskState",
        name: "previousState",
        type: "uint8",
      },
      {
        indexed: true,
        internalType: "address",
        name: "claimedBy",
        type: "address",
      },
    ],
    name: "TimeoutClaimed",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "escrowId",
        type: "uint256",
      },
    ],
    name: "abandonTask",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "escrowId",
        type: "uint256",
      },
    ],
    name: "acceptDelivery",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "escrowId",
        type: "uint256",
      },
    ],
    name: "cancelTask",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "escrowId",
        type: "uint256",
      },
    ],
    name: "claimAcceptanceTimeout",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "escrowId",
        type: "uint256",
      },
    ],
    name: "claimConfirmationTimeout",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "escrowId",
        type: "uint256",
      },
    ],
    name: "claimDeliveryTimeout",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "escrowId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expiredAt",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "platformSignature",
        type: "bytes",
      },
    ],
    name: "claimTask",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "escrowId",
        type: "uint256",
      },
    ],
    name: "confirmTask",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "taskHash",
        type: "bytes32",
      },
      {
        internalType: "uint64",
        name: "deliveryDurationSeconds",
        type: "uint64",
      },
      {
        internalType: "uint8",
        name: "maxRevisions",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "acceptanceWindowHours",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "criteriaCount",
        type: "uint8",
      },
      {
        internalType: "uint8[]",
        name: "fundWeights",
        type: "uint8[]",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "totalAmount",
        type: "uint256",
      },
    ],
    name: "createEscrow",
    outputs: [
      {
        internalType: "uint256",
        name: "escrowId",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "escrowId",
        type: "uint256",
      },
    ],
    name: "declineTask",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "escrowId",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "reasonHash",
        type: "bytes32",
      },
      {
        internalType: "bool[]",
        name: "criteriaResults",
        type: "bool[]",
      },
    ],
    name: "requestRevision",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "escrowId",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "deliveryHash",
        type: "bytes32",
      },
    ],
    name: "submitDelivery",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IClawPactEscrow__factory {
  static readonly abi = _abi;
  static createInterface(): IClawPactEscrowInterface {
    return new Interface(_abi) as IClawPactEscrowInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IClawPactEscrow {
    return new Contract(address, _abi, runner) as unknown as IClawPactEscrow;
  }
}
