/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IClawPactEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "abandonTask"
      | "acceptDelivery"
      | "cancelTask"
      | "claimAcceptanceTimeout"
      | "claimConfirmationTimeout"
      | "claimDeliveryTimeout"
      | "claimTask"
      | "confirmTask"
      | "createEscrow"
      | "declineTask"
      | "requestRevision"
      | "submitDelivery"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DeliveryAccepted"
      | "DeliverySubmitted"
      | "EscrowCreated"
      | "RevisionRequested"
      | "TaskAbandoned"
      | "TaskAutoSettled"
      | "TaskCancelled"
      | "TaskClaimed"
      | "TaskConfirmed"
      | "TaskDeclined"
      | "TaskSuspendedAfterDeclines"
      | "TimeoutClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "abandonTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "acceptDelivery",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimAcceptanceTimeout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimConfirmationTimeout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimDeliveryTimeout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTask",
    values: [BigNumberish, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createEscrow",
    values: [
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish[],
      AddressLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "declineTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRevision",
    values: [BigNumberish, BytesLike, boolean[]]
  ): string;
  encodeFunctionData(
    functionFragment: "submitDelivery",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "abandonTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptDelivery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimAcceptanceTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimConfirmationTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimDeliveryTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confirmTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "declineTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRevision",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitDelivery",
    data: BytesLike
  ): Result;
}

export namespace DeliveryAcceptedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    providerPayout: BigNumberish,
    platformFee: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    providerPayout: bigint,
    platformFee: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    providerPayout: bigint;
    platformFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeliverySubmittedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    deliveryHash: BytesLike,
    revision: BigNumberish,
    acceptanceDeadline: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    deliveryHash: string,
    revision: bigint,
    acceptanceDeadline: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    deliveryHash: string;
    revision: bigint;
    acceptanceDeadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowCreatedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    requester: AddressLike,
    taskHash: BytesLike,
    rewardAmount: BigNumberish,
    requesterDeposit: BigNumberish,
    token: AddressLike,
    deliveryDurationSeconds: BigNumberish,
    maxRevisions: BigNumberish,
    acceptanceWindowHours: BigNumberish,
    criteriaCount: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    requester: string,
    taskHash: string,
    rewardAmount: bigint,
    requesterDeposit: bigint,
    token: string,
    deliveryDurationSeconds: bigint,
    maxRevisions: bigint,
    acceptanceWindowHours: bigint,
    criteriaCount: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    requester: string;
    taskHash: string;
    rewardAmount: bigint;
    requesterDeposit: bigint;
    token: string;
    deliveryDurationSeconds: bigint;
    maxRevisions: bigint;
    acceptanceWindowHours: bigint;
    criteriaCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevisionRequestedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    reasonHash: BytesLike,
    criteriaResultsHash: BytesLike,
    currentRevision: BigNumberish,
    depositPenalty: BigNumberish,
    passRate: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    reasonHash: string,
    criteriaResultsHash: string,
    currentRevision: bigint,
    depositPenalty: bigint,
    passRate: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    reasonHash: string;
    criteriaResultsHash: string;
    currentRevision: bigint;
    depositPenalty: bigint;
    passRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskAbandonedEvent {
  export type InputTuple = [escrowId: BigNumberish, provider: AddressLike];
  export type OutputTuple = [escrowId: bigint, provider: string];
  export interface OutputObject {
    escrowId: bigint;
    provider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskAutoSettledEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    passRate: BigNumberish,
    providerShare: BigNumberish,
    requesterRefund: BigNumberish,
    platformFee: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    passRate: bigint,
    providerShare: bigint,
    requesterRefund: bigint,
    platformFee: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    passRate: bigint;
    providerShare: bigint;
    requesterRefund: bigint;
    platformFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCancelledEvent {
  export type InputTuple = [escrowId: BigNumberish, compensation: BigNumberish];
  export type OutputTuple = [escrowId: bigint, compensation: bigint];
  export interface OutputObject {
    escrowId: bigint;
    compensation: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskClaimedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    provider: AddressLike,
    confirmationDeadline: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    provider: string,
    confirmationDeadline: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    provider: string;
    confirmationDeadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskConfirmedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    provider: AddressLike,
    deliveryDeadline: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    provider: string,
    deliveryDeadline: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    provider: string;
    deliveryDeadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskDeclinedEvent {
  export type InputTuple = [escrowId: BigNumberish, provider: AddressLike];
  export type OutputTuple = [escrowId: bigint, provider: string];
  export interface OutputObject {
    escrowId: bigint;
    provider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskSuspendedAfterDeclinesEvent {
  export type InputTuple = [escrowId: BigNumberish, declineCount: BigNumberish];
  export type OutputTuple = [escrowId: bigint, declineCount: bigint];
  export interface OutputObject {
    escrowId: bigint;
    declineCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimeoutClaimedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    previousState: BigNumberish,
    claimedBy: AddressLike
  ];
  export type OutputTuple = [
    escrowId: bigint,
    previousState: bigint,
    claimedBy: string
  ];
  export interface OutputObject {
    escrowId: bigint;
    previousState: bigint;
    claimedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IClawPactEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): IClawPactEscrow;
  waitForDeployment(): Promise<this>;

  interface: IClawPactEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  abandonTask: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  acceptDelivery: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelTask: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimAcceptanceTimeout: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimConfirmationTimeout: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimDeliveryTimeout: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimTask: TypedContractMethod<
    [
      escrowId: BigNumberish,
      nonce: BigNumberish,
      expiredAt: BigNumberish,
      platformSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  confirmTask: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createEscrow: TypedContractMethod<
    [
      taskHash: BytesLike,
      deliveryDurationSeconds: BigNumberish,
      maxRevisions: BigNumberish,
      acceptanceWindowHours: BigNumberish,
      criteriaCount: BigNumberish,
      fundWeights: BigNumberish[],
      token: AddressLike,
      totalAmount: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  declineTask: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  requestRevision: TypedContractMethod<
    [escrowId: BigNumberish, reasonHash: BytesLike, criteriaResults: boolean[]],
    [void],
    "nonpayable"
  >;

  submitDelivery: TypedContractMethod<
    [escrowId: BigNumberish, deliveryHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "abandonTask"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "acceptDelivery"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelTask"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimAcceptanceTimeout"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimConfirmationTimeout"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimDeliveryTimeout"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimTask"
  ): TypedContractMethod<
    [
      escrowId: BigNumberish,
      nonce: BigNumberish,
      expiredAt: BigNumberish,
      platformSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confirmTask"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createEscrow"
  ): TypedContractMethod<
    [
      taskHash: BytesLike,
      deliveryDurationSeconds: BigNumberish,
      maxRevisions: BigNumberish,
      acceptanceWindowHours: BigNumberish,
      criteriaCount: BigNumberish,
      fundWeights: BigNumberish[],
      token: AddressLike,
      totalAmount: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "declineTask"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestRevision"
  ): TypedContractMethod<
    [escrowId: BigNumberish, reasonHash: BytesLike, criteriaResults: boolean[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitDelivery"
  ): TypedContractMethod<
    [escrowId: BigNumberish, deliveryHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DeliveryAccepted"
  ): TypedContractEvent<
    DeliveryAcceptedEvent.InputTuple,
    DeliveryAcceptedEvent.OutputTuple,
    DeliveryAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "DeliverySubmitted"
  ): TypedContractEvent<
    DeliverySubmittedEvent.InputTuple,
    DeliverySubmittedEvent.OutputTuple,
    DeliverySubmittedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowCreated"
  ): TypedContractEvent<
    EscrowCreatedEvent.InputTuple,
    EscrowCreatedEvent.OutputTuple,
    EscrowCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RevisionRequested"
  ): TypedContractEvent<
    RevisionRequestedEvent.InputTuple,
    RevisionRequestedEvent.OutputTuple,
    RevisionRequestedEvent.OutputObject
  >;
  getEvent(
    key: "TaskAbandoned"
  ): TypedContractEvent<
    TaskAbandonedEvent.InputTuple,
    TaskAbandonedEvent.OutputTuple,
    TaskAbandonedEvent.OutputObject
  >;
  getEvent(
    key: "TaskAutoSettled"
  ): TypedContractEvent<
    TaskAutoSettledEvent.InputTuple,
    TaskAutoSettledEvent.OutputTuple,
    TaskAutoSettledEvent.OutputObject
  >;
  getEvent(
    key: "TaskCancelled"
  ): TypedContractEvent<
    TaskCancelledEvent.InputTuple,
    TaskCancelledEvent.OutputTuple,
    TaskCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TaskClaimed"
  ): TypedContractEvent<
    TaskClaimedEvent.InputTuple,
    TaskClaimedEvent.OutputTuple,
    TaskClaimedEvent.OutputObject
  >;
  getEvent(
    key: "TaskConfirmed"
  ): TypedContractEvent<
    TaskConfirmedEvent.InputTuple,
    TaskConfirmedEvent.OutputTuple,
    TaskConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "TaskDeclined"
  ): TypedContractEvent<
    TaskDeclinedEvent.InputTuple,
    TaskDeclinedEvent.OutputTuple,
    TaskDeclinedEvent.OutputObject
  >;
  getEvent(
    key: "TaskSuspendedAfterDeclines"
  ): TypedContractEvent<
    TaskSuspendedAfterDeclinesEvent.InputTuple,
    TaskSuspendedAfterDeclinesEvent.OutputTuple,
    TaskSuspendedAfterDeclinesEvent.OutputObject
  >;
  getEvent(
    key: "TimeoutClaimed"
  ): TypedContractEvent<
    TimeoutClaimedEvent.InputTuple,
    TimeoutClaimedEvent.OutputTuple,
    TimeoutClaimedEvent.OutputObject
  >;

  filters: {
    "DeliveryAccepted(uint256,uint256,uint256)": TypedContractEvent<
      DeliveryAcceptedEvent.InputTuple,
      DeliveryAcceptedEvent.OutputTuple,
      DeliveryAcceptedEvent.OutputObject
    >;
    DeliveryAccepted: TypedContractEvent<
      DeliveryAcceptedEvent.InputTuple,
      DeliveryAcceptedEvent.OutputTuple,
      DeliveryAcceptedEvent.OutputObject
    >;

    "DeliverySubmitted(uint256,bytes32,uint8,uint64)": TypedContractEvent<
      DeliverySubmittedEvent.InputTuple,
      DeliverySubmittedEvent.OutputTuple,
      DeliverySubmittedEvent.OutputObject
    >;
    DeliverySubmitted: TypedContractEvent<
      DeliverySubmittedEvent.InputTuple,
      DeliverySubmittedEvent.OutputTuple,
      DeliverySubmittedEvent.OutputObject
    >;

    "EscrowCreated(uint256,address,bytes32,uint256,uint256,address,uint64,uint8,uint8,uint8)": TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;
    EscrowCreated: TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;

    "RevisionRequested(uint256,bytes32,bytes32,uint8,uint256,uint8)": TypedContractEvent<
      RevisionRequestedEvent.InputTuple,
      RevisionRequestedEvent.OutputTuple,
      RevisionRequestedEvent.OutputObject
    >;
    RevisionRequested: TypedContractEvent<
      RevisionRequestedEvent.InputTuple,
      RevisionRequestedEvent.OutputTuple,
      RevisionRequestedEvent.OutputObject
    >;

    "TaskAbandoned(uint256,address)": TypedContractEvent<
      TaskAbandonedEvent.InputTuple,
      TaskAbandonedEvent.OutputTuple,
      TaskAbandonedEvent.OutputObject
    >;
    TaskAbandoned: TypedContractEvent<
      TaskAbandonedEvent.InputTuple,
      TaskAbandonedEvent.OutputTuple,
      TaskAbandonedEvent.OutputObject
    >;

    "TaskAutoSettled(uint256,uint8,uint256,uint256,uint256)": TypedContractEvent<
      TaskAutoSettledEvent.InputTuple,
      TaskAutoSettledEvent.OutputTuple,
      TaskAutoSettledEvent.OutputObject
    >;
    TaskAutoSettled: TypedContractEvent<
      TaskAutoSettledEvent.InputTuple,
      TaskAutoSettledEvent.OutputTuple,
      TaskAutoSettledEvent.OutputObject
    >;

    "TaskCancelled(uint256,uint256)": TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;
    TaskCancelled: TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;

    "TaskClaimed(uint256,address,uint64)": TypedContractEvent<
      TaskClaimedEvent.InputTuple,
      TaskClaimedEvent.OutputTuple,
      TaskClaimedEvent.OutputObject
    >;
    TaskClaimed: TypedContractEvent<
      TaskClaimedEvent.InputTuple,
      TaskClaimedEvent.OutputTuple,
      TaskClaimedEvent.OutputObject
    >;

    "TaskConfirmed(uint256,address,uint64)": TypedContractEvent<
      TaskConfirmedEvent.InputTuple,
      TaskConfirmedEvent.OutputTuple,
      TaskConfirmedEvent.OutputObject
    >;
    TaskConfirmed: TypedContractEvent<
      TaskConfirmedEvent.InputTuple,
      TaskConfirmedEvent.OutputTuple,
      TaskConfirmedEvent.OutputObject
    >;

    "TaskDeclined(uint256,address)": TypedContractEvent<
      TaskDeclinedEvent.InputTuple,
      TaskDeclinedEvent.OutputTuple,
      TaskDeclinedEvent.OutputObject
    >;
    TaskDeclined: TypedContractEvent<
      TaskDeclinedEvent.InputTuple,
      TaskDeclinedEvent.OutputTuple,
      TaskDeclinedEvent.OutputObject
    >;

    "TaskSuspendedAfterDeclines(uint256,uint8)": TypedContractEvent<
      TaskSuspendedAfterDeclinesEvent.InputTuple,
      TaskSuspendedAfterDeclinesEvent.OutputTuple,
      TaskSuspendedAfterDeclinesEvent.OutputObject
    >;
    TaskSuspendedAfterDeclines: TypedContractEvent<
      TaskSuspendedAfterDeclinesEvent.InputTuple,
      TaskSuspendedAfterDeclinesEvent.OutputTuple,
      TaskSuspendedAfterDeclinesEvent.OutputObject
    >;

    "TimeoutClaimed(uint256,uint8,address)": TypedContractEvent<
      TimeoutClaimedEvent.InputTuple,
      TimeoutClaimedEvent.OutputTuple,
      TimeoutClaimedEvent.OutputObject
    >;
    TimeoutClaimed: TypedContractEvent<
      TimeoutClaimedEvent.InputTuple,
      TimeoutClaimedEvent.OutputTuple,
      TimeoutClaimedEvent.OutputObject
    >;
  };
}
