/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IClawPactTipJar {
  export type TipStatsStruct = {
    totalSent: BigNumberish;
    totalReceived: BigNumberish;
    totalFeesPaid: BigNumberish;
    tipsSentCount: BigNumberish;
    tipsReceivedCount: BigNumberish;
  };

  export type TipStatsStructOutput = [
    totalSent: bigint,
    totalReceived: bigint,
    totalFeesPaid: bigint,
    tipsSentCount: bigint,
    tipsReceivedCount: bigint
  ] & {
    totalSent: bigint;
    totalReceived: bigint;
    totalFeesPaid: bigint;
    tipsSentCount: bigint;
    tipsReceivedCount: bigint;
  };
}

export interface IClawPactTipJarInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "dailyTipSpent"
      | "setDailyTipCap"
      | "setMaxTipAmount"
      | "setPaused"
      | "setPlatformFeeBps"
      | "setPlatformSigner"
      | "setTreasury"
      | "tip"
      | "tipStats"
      | "usedNonces"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DailyTipCapUpdated"
      | "MaxTipAmountUpdated"
      | "PlatformFeeUpdated"
      | "PlatformSignerUpdated"
      | "TipSent"
      | "TippingPaused"
      | "TreasuryUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "dailyTipSpent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDailyTipCap",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxTipAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "setPaused", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "setPlatformFeeBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tip",
    values: [
      AddressLike,
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "tipStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usedNonces",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "dailyTipSpent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDailyTipCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxTipAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tip", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tipStats", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usedNonces", data: BytesLike): Result;
}

export namespace DailyTipCapUpdatedEvent {
  export type InputTuple = [oldCap: BigNumberish, newCap: BigNumberish];
  export type OutputTuple = [oldCap: bigint, newCap: bigint];
  export interface OutputObject {
    oldCap: bigint;
    newCap: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxTipAmountUpdatedEvent {
  export type InputTuple = [oldMax: BigNumberish, newMax: BigNumberish];
  export type OutputTuple = [oldMax: bigint, newMax: bigint];
  export interface OutputObject {
    oldMax: bigint;
    newMax: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeUpdatedEvent {
  export type InputTuple = [oldFeeBps: BigNumberish, newFeeBps: BigNumberish];
  export type OutputTuple = [oldFeeBps: bigint, newFeeBps: bigint];
  export interface OutputObject {
    oldFeeBps: bigint;
    newFeeBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformSignerUpdatedEvent {
  export type InputTuple = [oldSigner: AddressLike, newSigner: AddressLike];
  export type OutputTuple = [oldSigner: string, newSigner: string];
  export interface OutputObject {
    oldSigner: string;
    newSigner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TipSentEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    fee: BigNumberish,
    postId: string
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    amount: bigint,
    fee: bigint,
    postId: string
  ];
  export interface OutputObject {
    from: string;
    to: string;
    amount: bigint;
    fee: bigint;
    postId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TippingPausedEvent {
  export type InputTuple = [paused: boolean];
  export type OutputTuple = [paused: boolean];
  export interface OutputObject {
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [oldTreasury: AddressLike, newTreasury: AddressLike];
  export type OutputTuple = [oldTreasury: string, newTreasury: string];
  export interface OutputObject {
    oldTreasury: string;
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IClawPactTipJar extends BaseContract {
  connect(runner?: ContractRunner | null): IClawPactTipJar;
  waitForDeployment(): Promise<this>;

  interface: IClawPactTipJarInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  dailyTipSpent: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  setDailyTipCap: TypedContractMethod<
    [newCap: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMaxTipAmount: TypedContractMethod<
    [newMax: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPaused: TypedContractMethod<[paused: boolean], [void], "nonpayable">;

  setPlatformFeeBps: TypedContractMethod<
    [newFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPlatformSigner: TypedContractMethod<
    [newSigner: AddressLike],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  tip: TypedContractMethod<
    [
      recipient: AddressLike,
      amount: BigNumberish,
      postId: string,
      nonce: BigNumberish,
      expiredAt: BigNumberish,
      platformSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  tipStats: TypedContractMethod<
    [user: AddressLike],
    [IClawPactTipJar.TipStatsStructOutput],
    "view"
  >;

  usedNonces: TypedContractMethod<[nonceHash: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "dailyTipSpent"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setDailyTipCap"
  ): TypedContractMethod<[newCap: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxTipAmount"
  ): TypedContractMethod<[newMax: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPaused"
  ): TypedContractMethod<[paused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFeeBps"
  ): TypedContractMethod<[newFeeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformSigner"
  ): TypedContractMethod<[newSigner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tip"
  ): TypedContractMethod<
    [
      recipient: AddressLike,
      amount: BigNumberish,
      postId: string,
      nonce: BigNumberish,
      expiredAt: BigNumberish,
      platformSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tipStats"
  ): TypedContractMethod<
    [user: AddressLike],
    [IClawPactTipJar.TipStatsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "usedNonces"
  ): TypedContractMethod<[nonceHash: BytesLike], [boolean], "view">;

  getEvent(
    key: "DailyTipCapUpdated"
  ): TypedContractEvent<
    DailyTipCapUpdatedEvent.InputTuple,
    DailyTipCapUpdatedEvent.OutputTuple,
    DailyTipCapUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MaxTipAmountUpdated"
  ): TypedContractEvent<
    MaxTipAmountUpdatedEvent.InputTuple,
    MaxTipAmountUpdatedEvent.OutputTuple,
    MaxTipAmountUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeUpdated"
  ): TypedContractEvent<
    PlatformFeeUpdatedEvent.InputTuple,
    PlatformFeeUpdatedEvent.OutputTuple,
    PlatformFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformSignerUpdated"
  ): TypedContractEvent<
    PlatformSignerUpdatedEvent.InputTuple,
    PlatformSignerUpdatedEvent.OutputTuple,
    PlatformSignerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TipSent"
  ): TypedContractEvent<
    TipSentEvent.InputTuple,
    TipSentEvent.OutputTuple,
    TipSentEvent.OutputObject
  >;
  getEvent(
    key: "TippingPaused"
  ): TypedContractEvent<
    TippingPausedEvent.InputTuple,
    TippingPausedEvent.OutputTuple,
    TippingPausedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;

  filters: {
    "DailyTipCapUpdated(uint256,uint256)": TypedContractEvent<
      DailyTipCapUpdatedEvent.InputTuple,
      DailyTipCapUpdatedEvent.OutputTuple,
      DailyTipCapUpdatedEvent.OutputObject
    >;
    DailyTipCapUpdated: TypedContractEvent<
      DailyTipCapUpdatedEvent.InputTuple,
      DailyTipCapUpdatedEvent.OutputTuple,
      DailyTipCapUpdatedEvent.OutputObject
    >;

    "MaxTipAmountUpdated(uint256,uint256)": TypedContractEvent<
      MaxTipAmountUpdatedEvent.InputTuple,
      MaxTipAmountUpdatedEvent.OutputTuple,
      MaxTipAmountUpdatedEvent.OutputObject
    >;
    MaxTipAmountUpdated: TypedContractEvent<
      MaxTipAmountUpdatedEvent.InputTuple,
      MaxTipAmountUpdatedEvent.OutputTuple,
      MaxTipAmountUpdatedEvent.OutputObject
    >;

    "PlatformFeeUpdated(uint16,uint16)": TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
    PlatformFeeUpdated: TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;

    "PlatformSignerUpdated(address,address)": TypedContractEvent<
      PlatformSignerUpdatedEvent.InputTuple,
      PlatformSignerUpdatedEvent.OutputTuple,
      PlatformSignerUpdatedEvent.OutputObject
    >;
    PlatformSignerUpdated: TypedContractEvent<
      PlatformSignerUpdatedEvent.InputTuple,
      PlatformSignerUpdatedEvent.OutputTuple,
      PlatformSignerUpdatedEvent.OutputObject
    >;

    "TipSent(address,address,uint256,uint256,string)": TypedContractEvent<
      TipSentEvent.InputTuple,
      TipSentEvent.OutputTuple,
      TipSentEvent.OutputObject
    >;
    TipSent: TypedContractEvent<
      TipSentEvent.InputTuple,
      TipSentEvent.OutputTuple,
      TipSentEvent.OutputObject
    >;

    "TippingPaused(bool)": TypedContractEvent<
      TippingPausedEvent.InputTuple,
      TippingPausedEvent.OutputTuple,
      TippingPausedEvent.OutputObject
    >;
    TippingPaused: TypedContractEvent<
      TippingPausedEvent.InputTuple,
      TippingPausedEvent.OutputTuple,
      TippingPausedEvent.OutputObject
    >;

    "TreasuryUpdated(address,address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
  };
}
